pins:
  up_left:      18
  up_right:     11
  down_left:    22
  down_right:   15
  freeze_left:  16
  freeze_right: 13

settings:
  latitude: 51.5
  longitude: -0.12

schedule:
  skip_dates:
    - "2023-01-01"
  jobs:
    - name: 'both blinds freeze'
      job: 'both_blinds_freeze'
      runtime: '07:30:00'

    - name: 'both blinds partially down heat'
      job: 'both_blinds_freeze'
      runtime: '14:55:00'
      conditions:
        - type: weather
          kind: "sunny"
          temperature:
            operation: ">="
            value: 16

    - name: 'both blinds partially down test'
      job: 'both_blinds_down'
      runtime: '10:48:00'
      conditions:
        - type: weather
          temperature:
            operation: ">="
            value: 24

    - name: 'both blinds partially down high heat'
      job: 'both_blinds_down'
      runtime: '15:00:00'
      conditions:
        - type: weather
          temperature:
            operation: ">="
            value: 24

    - name: 'both blinds down sleep'
      job: 'both_blinds_down'
      runtime: 'sunset'

    - name: 'both blinds up'
      job: 'both_blinds_up'
      runtime: '09:00:00'
